### PR TITLE
Donate/withdraw separate wallets

### PR DESCRIPTION
**Pull request by ap-justin**
Ticket(s):
- https://github.com/AngelProtocolFinance/devops/pull/293
- merged
  * #2271 

## Explanation of the solution
* add `network` and `client` constants
* update endpoints 
* add `non-apes` wallets
- [x] test deposit
- [x] test withdraw ( to test on bridge fee update PR )

## Instructions on making this work

- run `yarn` or `yarn install` to install npm dependencies
- run `yarn run test --watchAll` to verify all tests still pass
- (optional) run `yarn run build` to verify the build passes
- run `yarn start` to start the webapp
-

## UI changes for review

When major UI changes are introduced with a PR, please include links to URLS to compare or screenshots demonstrating the difference and notify on design changes

### CODE REVIEW

**Comment by SovereignAndrey** [comment]
@ap-justin Please fix the one conflicting file and lmk if the withdraw work is done as well and I'll take a look. :+1: There's some fixes needed to the AWS PR regarding error handing, but it should not impact the web app.

**Comment by ap-justin** [comment]
> @ap-justin Please fix the one conflicting file and lmk if the withdraw work is done as well against the latest AWS PR and I'll take a look. 👍 There's some more fixes needed to the AWS PR regarding error handing, but it should not impact the web app as it's internal in nature.

@SovereignAndrey  merge conflicts have been resolve ser - I'll have the withdraw ready EOD 🤞

**Comment by SovereignAndrey** [comment]
> > @ap-justin Please fix the one conflicting file and lmk if the withdraw work is done as well against the latest AWS PR and I'll take a look. +1 There's some more fixes needed to the AWS PR regarding error handing, but it should not impact the web app as it's internal in nature.
> 
> @SovereignAndrey merge conflicts have been resolve ser - I'll have the withdraw ready EOD crossed_fingers

Thanks! Lmk when the withdraw is ready for a look.

**Comment by SovereignAndrey** [comment]
@ap-justin Couple small conflict clean ups and I think we can get this merged in!

**Comment by ap-justin** [comment]
> @ap-justin Couple small conflict clean ups and I think we can get this merged in!

@SovereignAndrey, resolved conflicts🤞

**Review by SovereignAndrey — APPROVED** [review]

**Pull request merged**
