### PR TITLE
Update yarn.lock

### PR DESCRIPTION
**Pull request by misicnenad**
## Explanation of the solution
`@aws-amplify/ui-react` was removed in PR https://github.com/AngelProtocolFinance/angelprotocol-web-app/pull/2770, need to update *yarn.lock*.

## Instructions on making this work

- run `yarn` or `yarn install` to install npm dependencies
- run `yarn run test --watchAll` to verify all tests still pass
- (optional) run `yarn run build` to verify the build passes

### CODE REVIEW

**Comment by ap-justin** [comment]
> @aws-amplify/ui-react was removed in PR https://github.com/AngelProtocolFinance/angelprotocol-web-app/pull/2770,

🤔 `yarn.lock` was already updated in that PR, RC-v1.9.2 works with the current lock file

**Comment by misicnenad** [comment]
> > @aws-amplify/ui-react was removed in PR #2770,
> 
> 🤔 `yarn.lock` was already updated in that PR, RC-v1.9.2 works with the current lock file

Oh, you're right, it really was :sweat_smile: Do you think we should drop this PR then?

**Comment by ap-justin** [comment]
> > > @aws-amplify/ui-react was removed in PR #2770,
> > 
> > 
> > 🤔 `yarn.lock` was already updated in that PR, RC-v1.9.2 works with the current lock file
> 
> Oh, you're right, it really was 😅 Do you think we should drop this PR then?

yes ser, yarn.lock changes should always be a result of changing something in package.json

**Comment by SovereignAndrey** [comment]
Closing this now.

**Pull request closed without merging**
