### PR TITLE
BG-954: Registration Flow changes

### PR DESCRIPTION
**Pull request by misicnenad**
## Instructions on making this work

- run `yarn` or `yarn install` to install npm dependencies
- run `yarn run test --watchAll` to verify all tests still pass
- (optional) run `yarn run build` to verify the build passes
- run `yarn start` to start the webapp
**<<1. Register + sign up>>**
- make sure you're signed out
- go to http://localhost:4200/register
- you're redirected to sign in page
- click on "Sign Up"
- complete the sign up process
- **verify you're redirected to the Welcome page**
**<<2. Register + sign up>>**
- make sure you're signed out
- go to http://localhost:4200/register
- you're redirected to sign in page
- sign in
- **verify you're redirected to the plain */register* page**
**<<3. Register + sign in>>**
- make sure you're signed in
- type http://localhost:4200/register/welcome in the search bar
- **verify you're redirected to the Welcome page (no longer need to go through */register*)**

### CODE REVIEW

**Review by SovereignAndrey — CHANGES_REQUESTED** [review]
The Signin flow worked fine, landing me on the /register page. 
The Signup flow did not work for me however. I got the following error after confirming my email with confirm code: 
```
ERROR
to.pathname.includes is not a function
TypeError: to.pathname.includes is not a function
    at resolveTo (http://localhost:4200/static/js/bundle.js:20439:44)
    ```

**Comment by misicnenad** [comment]
> The Signin flow worked fine, landing me on the /register page. The Signup flow did not work for me however. I got the following error after confirming my email with confirm code:
> 
> ```
> ERROR
> to.pathname.includes is not a function
> TypeError: to.pathname.includes is not a function
>     at resolveTo (http://localhost:4200/static/js/bundle.js:20439:44)
> ```
> 
> I can _manually_ get to the /registration/welcome page OK.

@SovereignAndrey can't repro, can you post exact repro steps?

**Comment by SovereignAndrey** [comment]
> > The Signin flow worked fine, landing me on the /register page. The Signup flow did not work for me however. I got the following error after confirming my email with confirm code:
> > ```
> > ERROR
> > to.pathname.includes is not a function
> > TypeError: to.pathname.includes is not a function
> >     at resolveTo (http://localhost:4200/static/js/bundle.js:20439:44)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I can _manually_ get to the /registration/welcome page OK.
> 
> @SovereignAndrey can't repro, signup works fine on my end, can you post exact repro steps?

I followed your steps at top of the PR for `<<1. Register + sign up>>`.

**Review by ap-justin — APPROVED** [review]
@SovereignAndrey, found no discrepancy to expected flows Nenad listed in this PR

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey, found no discrepancy to expected flows Nenad listed in this PR

Awesome! Let's gooooo then. :rocket:

**Pull request merged**
