### PR TITLE
Remove unncessary evm packages ( low priority )

### PR DESCRIPTION
**Pull request by ap-justin**
Ticket(s): N/A

This is to bring changes in 1651 in batches
* #1651 

This batch focuses on directly using `injected providers` (from wallet extension) and  `walletconnect.sendRequest` that implements `EIP` specs. This removes the need for additional layers like `ethers/providers` or `@walletconnect/web3-provider`

## Explanation of the solution
* remove `@ethersproject/provider` in favor of injected `window.provider` + `EIP` methods
* remove additional package `@walletconnect/web3-provider` and just use `walletconnect.sendCustomRequest` + `EIP` methods
* remove `ethereum-multicall + @ethersproject/contract` for fetching `erc20` balances and just use `@ethersproject/abi` + `erc20.json abi` + related `EIP` methods

## Others
* use `node-stdlib-browser` instead of installing individual browser polyfill. Nonetheless, only used `fallback/alias` is included in build. This PR removes the use for `assert` , `os`, `http` , `https`

### Tests
- [x] mobile wallet connection
- [x] mobile wallet connection persistence (remains connecte on browser reload)

--transactions
- [x] erc20 transfer with extension
- [x] erc20 transfer with mobile via wallet-connect
- [x] send native with extension
- [x] send native with mobile via wallet-connect  

--query
- [x] native balance
- [x] erc20 balance

 

## Instructions on making this work

- run `yarn` or `yarn install` to install npm dependencies
- run `yarn run test --watchAll` to verify all tests still pass
- (optional) run `yarn run build` to verify the build passes
- run `yarn start` to start the webapp
-

## UI changes for review

When major UI changes are introduced with a PR, please include links to URLS to compare or screenshots demonstrating the difference and notify on design changes

### CODE REVIEW

**Comment by misicnenad** [comment]
@ap-justin the changes sound useful. How big is the build size difference with these pkgs removed?

**Comment by ap-justin** [comment]
> @ap-justin the changes sound useful. How big is the build size difference with these pkgs removed?

@misicnenad, about `200kb` ser

**Comment by SovereignAndrey** [comment]
@ap-justin Please fix the conflicts and we can get this in after that. :+1:

**Comment by ap-justin** [comment]
> 8f5bfd5

done ser https://github.com/AngelProtocolFinance/angelprotocol-web-app/pull/1897/commits/8f5bfd52f1519e5782104f926b161873b90f3d12

**Review by SovereignAndrey — APPROVED** [review]

**Pull request merged**
